#######################################
############  usuário  ################
#######################################


# Criar usuário
POST http://127.0.0.1:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 11,
    "nome": "bianca",
    "email": "teste@gmail.com",
    "senha": "265"
}

#######################################
# Pegar usuário
GET http://127.0.0.1:8000/usuario?id=11 HTTP/1.1
content-type: application/json

####### Usuario pelo nome #############

GET http://127.0.0.1:8000/usuario/nome?nome=bianca
content-type: application/json


#######################################
############  endereço  ###############
#######################################

# Criar endereço
POST http://127.0.0.1:8000/endereco/2 HTTP/1.1
content-type: application/json

{
    "rua": "Rua jose gomes ",
    "cep": "99999-999",
    "cidade": "Goiania",
    "estado": "GO"
}

#######################################
############  produto  ################
#######################################

# Criar produto
POST http://127.0.0.1:8000/produto HTTP/1.1
content-type: application/json

{
    "id": 9,
    "nome": "Sorvete",
    "descricao": "Doce gelado",
    "preco": 9.99
}